- waflib/Tools/perl.py
Should cover Fedora, the rest of the world, and those that only have xsubpp in PATH.
> Find xsubpp in order, privlib, vendorlib and path.

- waflib/Tools/python.py
Should /usr/local/.../site-packages not be in sys.path in some
platform, a user would pass --pythondir, and --pythonarchdir to
waf when compiling, or modify sys.path.
This makes waf work more predictable, as when passing --prefix
parameter to the build, everything will be installed under this
directory.
> Use same prefix convention for python as with ruby and perl.

- waflib/extras/cpplint.py
cpplint: fixed import. The version on pypi is now up to date and works with Python3.
> cpplint: fixed import.

- waflib/extras/cpplint.py
cpplint: import first like it did previously. fallback on the new import if it fails.
> cpplint: keep the old import

- waflib/Tools/qt5.py
In Qt 5.4 on Windows, wrong include paths and defines were added to the compiler command line due to the naming of the Qt 5.4 libraries.  For example, a library is named 'Qt5Core.lib', but the corresponding include path is still '$QT5_ROOT/include/QtCore'.  The include path provided on the command line was incorrectly given as '$QT5_ROOT/include/Qt5Core' instead.   Also, defines such as QT_CORE_LIB were appearing as QT_5CORE_LIB.
> qt5: cope with library names like 'Qt5Core' instead of 'QtCore5'

- waflib/Tools/vala.py
The actual compiler option is named `--thread`, not `--threading`.
Renames the waf option for 'thread': it shouldn't be breaking anyone as it was not even working.
Maybe `--threading` this was an old option for valac? It would be really nice to double check before merging.
> Fix the '--threading' option for valac.

- demos/c++/wscript
- waflib/Tools/ccroot.py
- waflib/Tools/fc_config.py
- waflib/Tools/gcc.py
- waflib/Tools/gxx.py
For ELF binaries (e.g., Linux): default compatible version (SONAME =
`<library-name>.so.<MAJOR>`) can be specialized using additional `cnum`
parameter to `<library-name>.so.<MAJOR>.<MINOR>` or
`<library-name>.so.<MAJOR>.<MINOR>.<PATCH>`.
For Mach-O binaries (e.g., OS X):
- (bugfix) install-name points to compatible version (not absolute path
to a non-versioned library)
- Default install-name `<install-path>/<library-name>.<MAJOR>.dylib` can
be specialized using `cnum` parameter to
`<install-path>/<library-name>.<MAJOR>.<MINOR>.dylib` or
`<install-path>/<library-name>.<MAJOR>.<MINOR>.<PATCH>.dylib`
- `-Wl,-compatibility_version` and `-Wl,-current_version` flags use
version from cnum/vnum (default cnum is `vnum.split('.')[0]`)
- When `vnum` is not specified, `-Wl,-compatibility_version` and …
> Change with shared library compatibility version handling

- waflib/Configure.py
Currently, attempting to load a tool in the ```Configure``` context enters it into a cache and prevents further attempts at loading it, regardless of the ```tooldir``` argument. This prevents users from attempting to load the tool from somewhere else, if an initial attempt at loading the tool fails.
The approach taken in this PR allows repeated load attempts from different ```tooldir```s. An alternative approach would be to only enter the tool into the cache if the load attempt succeeds, which may or may not be more desirable.
> Add tooldir to cache-check on loading module in Configure context.

- tests/macplist/src/main.c
- tests/macplist/wscript
- waflib/Tools/c_osx.py
Rather than using an inline interpolated heredoc string, or generating
the file in a pre-build step, allow the macplist task itself to
perform string interpolation on the contents of a plist file.
> [macplist]: interpolate file

- waflib/Context.py
Before, they would crash because Python was trying to format `%r` using the tuple, which had more than one element.
> Fix exec_command and cmd_and_log when cmd is tuple

- waflib/Configure.py
- waflib/Context.py
Currently, when a user attempts to load a waf tool, waf will load any module with the given name, which can be found on ```sys.path```. Specifying a ```tooldir``` does prevent loading from ```waflib.Tools``` and ```waflib.extras```, but not from any location already on the path.
The ability to load waf tools from site packages and other locations on the path may be desired in general, but searching the path, even when ```tooldir``` is specified, breaks my use case of first attempting to load a tool from a specific directory and then falling back to the standard waf tools, if that fails. In my case, a *python module* gets loaded from ```sys.path```, instead of the *waf tool*, which I want.
To me, when specifying a ```tooldir``` the search behaviour should **either** be _identical_ to the …
> Disable regular sys.path when loading tool with specified tooldir.

- waflib/Tools/msvc.py
and stop when one is found that matches the user's options. This happens during autodetect only
when the new option msvc_lazy_autodetect or env.MSVC_LAZY_AUTODETECT is set.
These version uses a lazytup class modified from Thomas in an effort to not break all the gather* APIs. Because these get saved in the config set, repr is overridden to display the real tuple value for targets that have been evaluated and a default value for those that have not.
> Optionally lazily check installed msvc compilers' environments

- waflib/Tools/msvc.py
This branch includes two patches. The first disables saving MSVC_INSTALLED_VERSIONS after lazy detection, because in that case the targets have not all been evaluated and so there are a lot of empties--see #1611.
The second updates get_msvc_versions to evaluate all targets if called directly. This enables saving MSVC_INSTALLED_VERSIONS and printing them even if lazy detection is otherwise set. Note the other gather_* functions still return the full list of lazytups if called directly.
Neither one of these is strictly needed for anything I'm doing, but if it's an improvement over the behavior currently in master, feel free to take it.
> Don't save MSVC_INSTALLED_VERSIONS for lazy detection

- waflib/Tools/msvc.py
This branch in two patches fixes the structure of WinCE and winphone targets in the versions list. See #1616. I am not addressing the issue mentioned in which additional environment variables are needed to successfully configure and build. Someone with a working project to test or knowledge of exactly what paths need to end up in the config set would need to address that part.
> Consolidate mobile targets

- waflib/Tools/c_config.py
The check for C functions fails with '-Werror' in GCC (5.2).
The cast here triggers an error:
```
return (int)p;
```
error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
The conversion here triggers another error with '-pedantic -Werror':
```
p=(void*)(%s);
````
error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
This patch fixes both errors.
Signed-off-by: Mohammad Alsaleh <CE.Mohammad.AlSaleh@gmail.com>
> c_config: Avoid warnings/errors when checking for C functions

- waflib/Tools/suncc.py
`-Kpic` had been used to generate position-indenpendent code for Sun CC.
This permits only 2^10 unqiue symbols per shared object on 64-bit
systems.  This is an unreasonably small default. Switching to `-KPIC`
increases the number to 2^29.
According to
http://docs.oracle.com/cd/E37069_01/html/E37074/bjapp.html#OSSCGbjatt,
both `-Kpic` and `-KPIC` have been deprecated, and the `-xcode` option
should be used instead. `-xcode` has been available since at least Sun
Studio 8.
> Update the pic build flag used for Sun CC

- docs/sphinx/conf.py
The 'default' theme has been renamed to 'classic' for Sphinx >= 1.3.
This should fix #1645.
> Select HTML theme depending on Sphinx version.

- demos/xcode6/src/MyLib/ObjcClass.m
- demos/xcode6/wscript
- waflib/extras/xcode6.py
This is a new Pull request, based on #1651 but has been re-made since, there were some commit issues in the previous.
* The bld(sources='') has been replaced by bld(source_files={}). See demo for example.
* The bld(export_headers=..) argument now supports folders (not only files) - this tells XCode to ship these headers with a .framework target
* Added a bld(install='/path/...') argument that tells XCode to copy the target to desired path after build.
* Fixed an issue where a dependency framework target in bld(use='mytarget') was added both in LD_FLAGS and LinkWithFramework Buildphase. Now it's only added to the latter.
> XCode 6 generator updates and fixes

- playground/json/test.json
- playground/json/wscript
- waflib/Node.py
This adds `write_json` and `read_json` functions to the Node class.
You can run the playground example with `../../waf-light`:
```
[waf/playground/json] python2 ../../waf-light
Waf: Entering directory `/home/matt/git/github/waf-project/waf/playground/json/build'
('Read', {'array': [1, 2, 'abc', 4.8, None], 'boolean': True, 'dict': {'integer': 1, 'float': 4.8, 'string': 'Hello, world!'}})
('Wrote', '{"new_key":{"number":199},"array":[1,2,"abc",4.8,null],"boolean":true,"dict":{"integer":1,"float":4.8,"string":"Hello, world!"}}')
Waf: Leaving directory `/home/matt/git/github/waf-project/waf/playground/json/build'
'build' finished successfully (0.004s)
[waf/playground/json] python3 ../../waf-light
Waf: Entering directory `/home/matt/git/github/waf-project/waf/playground/json/build'
Read …
```
> Node JSON functions

- waflib/Tools/fc_config.py
As discussed in #1672 here is a patch to ignore error codes from Fortran compilers when obtaining the version string.
> Ignore error codes from cmd_and_log in getoutput for Fortran compilers

- waflib/Tools/ifort.py
as discussed in #1672 this change loosens and simplifies the regex for the version string of the ifort. It works at least with Intel 15 on Linux 64 bit.
> Regex change proposed by apthorpe

- waflib/Tools/ifort.py
Instead, try invoke search for ar after looking for xiar.
Ifort comes with its own archiver which is required for interprocedural optimizations, if I remember correctly. This archiver xiar would be preferred to use for ifort, thus the configure for ifort looked for xiar instead of using find_ar. However, it also set unconditionally the ARFLAGS to rcs, which causes trouble if the archiver is not actually xiar and the user gets robbed of the possibility to set those flags manually. This change now removes the unconditional setting of rcs and instead invokes find_ar to look for the archiver if it was not already found and sets the flags accordingly.
I hope this is the correct way to go about.
Maybe the find_ar should instead take an argument for the archiver name to look for?
> Do not set the ARFLAGS unconditionally to rcs for ifort.

- waflib/extras/fc_nag.py
The nagfor compiler (as of current version 6.0) uses according to the man page the option `-V` to query compiler version. Waf uses `-v` instead, where nagfor expects also a source file name at the command line and generates an exit code != 0 when not present. This caused in waf 1.8.17 failure when detecting nagfor. Although recent patches in `fc_config.py` work around this by accepting non-zero exit codes, one should probably still use the correct flag.
> Fixing version flag for NAG compiler.

- waflib/Tools/ifort.py
So, here is what I did to fix my setting. I think it would be good to set this, as all Fortran compilers provide it and it would be a little surprising to not have it for ifort on windows. However, in my wscript I anyway need to check for win or not. Thus, it is not strictly necessary to have this.
> Set FC_NAME also in find_ifort_win32.

- waflib/extras/netcache_client.py
This ensures that, for example, executable files that are fetched from
the cache end up with the right permissions.
> Do chmod in netcache post_run

- waflib/extras/netcache_client.py
When a task class has a true value for the nocache attribute,
setup_nocache doesn't decorate the run() and post_run() methods of the
class. In most cases, however, that's not enough to disable caching
because the base Task class is still modified; any class based on Task
which doesn't override these methods will still use caching even if it
sets nocache to True. This is solved by having the decorated versions of
run() and post_run() do nothing except call the original version of the
method when the task object has a true value for self.nocache.
> No-op in netcache run/post_run if nocache is true

- waflib/Tools/c_config.py
Add support to a really old Sun WorkShop C compiler version 5.0
> Add SUN cc compiler version 5.0

- waflib/Tools/d_scan.py
When importing `path.to.module` in D, both `path/to/module.d` and `path/to/module/package.d` should be tried.
> Make D dependency scanner aware of package.d files

- waflib/extras/cppcheck.py
The following error occurring when we try to run the cppcheck tool on windows.
As we see in the error message, the command is not well formed.
> **WafError:**
>     Command "['C:\\\\Program Files (x86)\\\\Cppcheck\\\\cppcheck.exe'] --inconclusive --report-progress --verbose --xml ..."
> **returned 1**
> Cppcheck tool - Fix creation of invalid command on windows

- playground/boost_log/main.cpp
- playground/boost_log/wscript
- waflib/extras/boost.py
- Output detected version of boost in dot-form (e.g., 1.56.0, instead of 1_56)
- Fix Boost.Log library detection:
* when linking to shared library, BOOST_LOG_DYN_LINK needs to be defined
* when linking to non-multithreaded version, BOOST_LOG_NO_THREADS needs to be defined
(see http://www.boost.org/doc/libs/1_60_0/libs/log/doc/html/log/installation/config.html)
> Boost module enhancements and fixes

- waflib/ConfigSet.py
That allows users to use nested transactions.
An very simple example of use is:
```python
def configure(cfg):
env = cfg.env
env.stash()
try:
env.X = 1
env.stash()
try:
env.Y = 2
except:
env.revert()
else:
env.commit()
raise
except:
env.revert()
else:
env.commit()
```
> Add commit() method to ConfigSet

- waflib/Tools/javaw.py
Allow to give a jar manifest as node or string.
> java tool : allow manifest to be a node

- waflib/extras/msvs.py
This patch adds support for an easier syntax for customizing which
version of Visual Studio msvs.py targets. It also allows users to
specify the PlatformToolset property on projects generated by waf. This
is necessary in order to properly generate projects for newer versions
of Visual Studio such as 2013 and 2015.
Example Syntax:
To generate a solution targeted at visual studio 2013 use the following
example:
```Python
class msvs_2013(msvs.msvs_generator):
cmd = 'msvs2013'
numver = '13.00'
vsver = '2013'
platform_toolset_ver = 'v120'
```
This will populate the associated fields correctly for msvs 2013.
> Add PlatformToolset ver. to msvs proj template

- waflib/Tools/msvc.py
I noticed the default was still evaluating all msvc targets and tracked it down to a typo in this check.
Changing the conditional was also required to achieve saving MSVC_INSTALLED_VERSIONS to the configuration.
I wonder if the default in `getattr(Options.options, 'msvc_lazy', True)` in a couple places could be removed on the assumption that the option defaults the value at the beginning of the program.
> Enable lazy Visual Studio detection by default: one missed spot.

- utils/waf.bat
Some Windows python distributions (like Anaconda) add a registry entry in InstallPath without a trailing backslash (i.e C:\Python\Anaconda2 rather than C:\Python\Anaconda2**\**)
For those distributions, REG_PYTHON is invalid
- waf.bat configure
- Using C:\Python\Anaconda2python.exe
- '"C:\Python\Anaconda2python.exe"' is not recognized as an internal or external command, operable program or batch file.
This one liner adds a backslash to the directory variable if not present...
> Fixes missing backslash for REG_PYTHON_DIR

- playground/swig/wscript
Fix a comment regarding the commandline options for swig, since '-dump_classes' was renamed to '-debug-classes'. Please see http://www.swig.org/Release/CHANGES for further details.
> fix comment regarding commandline options for swig

- waflib/extras/doxygen.py
DOXY_FILE_PATTERNS is generated as a string but then used as an array when using the RECURSIVE option, therefore the generated patterns for files to be searched are wrong. Convert it into an array with split() therefore to have correct patterns.
> Wrong search patterns generated when recursive doxygen generation is used with default file patterns

- waflib/Tools/qt5.py
Just fix the documentation examples, as the code is correct and working.
> qt5: Fix usage examples as libraries in qt5 are named QT5XXX and not QTXXX as in qt4 (ie. QT5WIDGETS instead of QTWIDGETS)

- waflib/Tools/waf_unit_test.py
Fix: when using the ut_cmd or Option --testcmd, if the test command line has parameters (added for example with the ut_fun method as in the examples) this will be lost as just ut_exec[0] was used. Now join the command line before using it in substition.
> Fix: when using the ut_cmd or Option --testcmd, parts of test command line may get lost

- waflib/Scripting.py
Hi!
The reconfiguration shouldn't invalidate the user's build options. For example, if the project has more than one task generator and autoconfig is set as 'clobber', then a reconfiguration triggered when the command `waf --targets=foo` is issued would make the build command post all taskgens instead of only the one named as 'foo'. This PR intends to fix that.
Best regards,
Gustavo Sousa
> Fix autoconfig

- waflib/Tools/waf_unit_test.py
When running a unit test if LD_LIBRARY_PATH is undefined in the local environment the execution will end with an error:
```
File "/home/fede/waf/wafm/waf-master/.waf-1.9.0-6564ab2e0480b52e07ca5175f6e3287e/waflib/TaskGen.py", line 111, in post
v()
File "/home/fede/waf/wafm/waf-master/.waf-1.9.0-6564ab2e0480b52e07ca5175f6e3287e/waflib/Tools/waf_unit_test.py", line 49, in make_test
add_path('LD_LIBRARY_PATH')
File "/home/fede/waf/wafm/waf-master/.waf-1.9.0-6564ab2e0480b52e07ca5175f6e3287e/waflib/Tools/waf_unit_test.py", line 42, in add_path
dct[var]=self.ut_paths+dct[var]
KeyError: 'LD_LIBRARY_PATH'
```
Just handle this by putting an empty string as default
> Manage case in unit_test running when LD_LIBRARY_PATH is not already defined in the environment

- waflib/Tools/qt5.py
When a header file is generated from .ui files the target generated (with the pattern ui_XXXX.h) is missing the full path, leading to possible name clashes and in general to a pollution of the build directory structure which may require additional unwanted includes to be added.
So for example
```
a/panel.ui
b/panel.ui
c/panel.ui
```
will all get generated as `build/ui_panel.h`, therefore leading to a name clash. Even if the name didn't collide one would have to always include "." in all three cases to make it work.
The little patch will preserve the directory structure leading to generation:
```
build/a/ui_panel.h
build/b/ui_panel.h
build/c/ui_panel.h
```
> qt5: uic generation task missing path to target, name conflict possible

- playground/pytest/src/foo/foo.py
- playground/pytest/test/test_foo.py
- playground/pytest/wscript
- waflib/Tools/pytest.py
Regarding issue #1765, I've created as per your suggestion a _pytest_ feature.
It takes care of populating the `PYTHONPATH`  and _dep_nodes_ for dependent task generators but does not make a decision on a specific test framework so it's up to the user to specify a _ut_str_.
Example use where _foo_ could be a Python task generator or a task generator with a _link_task_:
def build(bld):
bld(features      = 'pytest',
use           = 'foo',
pytest_source = bld.path.ant_glob('test/*.py'),
ut_str        = '${PYTHON} -B -m unittest discover')
Let me know if you want something changed.
> Python unit test support via `pytest' feature.

- waflib/Scripting.py
Hi,
Otherwise, the user would receive an error due to a FileNotFoundError exception.
Best regards,
Gustavo Sousa
> Set do_config as True if file is not found

- playground/pyqt5/res/test.txt
- playground/pyqt5/sampleRes.qrc
- playground/pyqt5/src/firstgui.ui
- playground/pyqt5/src/sample.py
- playground/pyqt5/wscript
- waflib/extras/pyqt5.py
Added pyqt5 support as discussed in #1772 as separate extra with playground example for .ui and .qrc generation.
Missing from discussion: to be eventually added in a future commit prevention of extension clash (just in case both pyqt5 and c++ qt5 are used at the same time)
> pyqt5 extra to support qt5 files to python conversion

- waflib/extras/boost.py
* find libname pattern "libboost_python-2.7.so"
Change-Id: I19a66a5992f7d077c2ed8e35e26e414ab194a7e6
> Add suppport for finding lib boost_python in gentoo

- waflib/Build.py
If something was added to SAVED_ATTRS, the next build command failed because
the saved dictionary in the pickle file didn't have that new key.
> Fix error when adding new items to SAVED_ATTRS

- waflib/Task.py
Currently waf prints the task and the command when a build task failed. Especially with linker errors this results in a lot of output. For example when linking hundreds of object files `str(self)` lists all of them as inputs and `last_cmd` lists all of them again as they are passed to the linker.
This PR changes the behavior so that the verbose output is only shown when running with at least `-v`.
> Less verbose output when a task failed if not running with -v

- waflib/Context.py
Sometimes my tasks have invalid characters in their output (for example a source file which is encoded in an encoding different from `sys.stdout.encoding` or a test program which has a bug). Currently waf fails with an exception without showing me the output at all.
This PR uses `errors='replace'` which will replace any decoding errors with ? characters, just as most terminals would do anyway. AFAIK it's only available since Python 2.7, that's why I've added the try/except.
I've tested this with Python 3.5 on Windows and on CentOS 6 with Python 2.6.
> Don't fail on output decoding errors

- wscript
Sometimes it is useful to be able to add a module to waf as a tool.
Using this patch one can use `./waf-light configure build --tools /tmp/mytool`
This will add the files under /tmp/mytool under /waflib/extras/mytool. Such
that they can be imported in a wscript as `from waflib.extras import mytool`.
> Allow using directories as waf tools

- waflib/Task.py
- waflib/TaskGen.py
- waflib/Utils.py
Besides hashing `functools.partial` objects, I needed to tweak `process_rule` to take it into account.  The reason is that normally a function defined inside a class becomes a bound method automatically when accessed through an instance, but not so for functools.partial.  Docs say:
>  partial objects defined in classes behave like static methods and do not transform into bound methods during instance attribute look-up.
> Accept functools.partial() as a task rule #1862

- waflib/extras/c_emscripten.py
When linking with static libraries emscripten would consider .a files not .bc
> correct static lib extension for emscripten

- waflib/Tools/python.py
This might be useful to force the installation of python objects to site-packages, i.e.: not in `__pycache__` directory. I've found this need when using buildroot with the option ".pyc compiled sources only" selected. Apparently buildroot do nothing for objects placed at `__pycache__` directory.
> Tools/python: add option --nopycache

- waflib/extras/boost.py
Uses proper filename conventions, allows static ABI to be specified, as requested per #1699
> Fix boost library naming conventions

- waflib/extras/c_emscripten.py
Emscripten requires space after '-o' flag. This fixes it.
> Fixed '-o' flag for emscripten/clang

- waflib/extras/c_emscripten.py
As per previous similar pull requests this fixes issues with latest versions of emscripten which expects a space after '-o' flag.
> Added '-o' flag for emscripten linker

- waflib/Tools/qt5.py
This is to simplify the management of additional QT5 libraries installed on the system but not present in the default QT5 packaging and therefore already defined in the extra. To automatically leverage on the libraries definition for configuration search and dependency management.
example usages:
waf configure --qtextralibs Qt5OpcUA
waf configure --qtextralibs Qt5OpcUA,Qt5Dummy
> qt5: add --qtextralibs option to add qt5 custom libraries on the system to the default libraries list present in the qt5 tool

- waflib/Tools/javaw.py
If the compat attribute was an integer the build would throw an exception due to it not being iterable.  Convert it to a string to be more flexible.
> Allow numbers for Java compat attribute

- waflib/Build.py
See #1870.
I made the message a little simpler, so that it doesn't include `waf configure`.
Sorry that I didn't reply to your question in my previous PR #1893, I didn't find the time last week.
> Improve error message about version mismatch

- waflib/Tools/c_osx.py
Without the fix, the following error is being generated:
```
✔  22:14 ~/Devel/ndn/ChronoShare [ blabla L | ✚ 2 ] $ ./waf install
Waf: Entering directory `/Users/cawka/Devel/ndn/ChronoShare/build'
Waf: Leaving directory `/Users/cawka/Devel/ndn/ChronoShare/build'
Traceback (most recent call last):
File "/Users/cawka/Devel/ndn/ChronoShare/.waf-1.9.8-6bd4f1773040d5281015a793f518c0ed/waflib/Scripting.py", line 120, in waf_entry_point
run_commands()
File "/Users/cawka/Devel/ndn/ChronoShare/.waf-1.9.8-6bd4f1773040d5281015a793f518c0ed/waflib/Scripting.py", line 181, in run_commands
ctx=run_command(cmd_name)
File "/Users/cawka/Devel/ndn/ChronoShare/.waf-1.9.8-6bd4f1773040d5281015a793f518c0ed/waflib/Scripting.py", line 172, in run_command
ctx.execute()
File …
```
> c_osx: Fix install task for mac_files

- wscript
I fixed an issue regarding the tool directories feature that was added by my friend @mortenvp here:
https://github.com/waf-project/waf/pull/1829
I tried to build a waf binary on Windows with some tool directories added, and the resulting binary worked fine on Windows, but when I copied it to a Unix system it failed to find the embedded tools.
It turns out that we stored a Windows-style path in `directory_files` that contained `\` path separators, and these paths were used in `tarinfo.name`. So when Python extracted the archive on a Unix system, the stored `\` path separators created an obvious problem.
The problem is fixed below by always using the `/` path separator. I also added a comment to explain the problem.
> Use platform-independent path separators when adding tool directories

- waflib/Options.py
Currently the colored output of Waf can be disabled by the environment variable `NOCOLOR`. Especially when running Waf inside a CI server (which logs the output), it is required to pass `--color=yes`. This gets tedious when you have multiple invocations, e. g.
```sh
./waf --color=yes configure
./waf --color=yes build
./waf --color=yes test
```
Therefore an environment variable to force colored output would be handy.
In order not to have too many different env variables one has to remember, I hope that `CLICOLOR` and `CLICOLOR_FORCE` can become some kind of standard, see https://bixense.com/clicolors/. CMake also supports `CLICOLOR_FORCE`, so I think it might be a good fit for Waf, too. Also the [ANSI plugin for Sublime](https://github.com/aziz/SublimeANSI) already encourages to set …
> Support CLICOLOR(_FORCE) to control colored output

- wscript
#1940 Try to find python.exe via call to where, but if it's not located use py.exe instead.
> waf.bat changed to support Python3 installation on Windows.

- waflib/extras/eclipse.py
Tried to improve the Eclipse integration for Python so using pydev:
-) use standard variable PROJECT_DIR_NAME to make it more standard/portable
-) generate paths to python modules configured in wscripts so objects are then correctly found and resolved in the IDE without any additional manual configuration needed
> eclipse: python integration improvements

- waflib/extras/cpplint.py
> cpplint: fix Python 2 import name collision using `absolute_import`

- waflib/extras/cpplint.py
The `cpplint` tool contains classes which are old style `classobj` rather than the new style `type` in Python 2.6 or lower. These classes call `super()`, which expects a `type` argument, causing a TypeError.
Inheriting directly from `object` (in addition to respective superclasses) solves the issue.
> cpplint: safely call super() on Python <= 2.6

- waflib/Tools/cs.py
The cs tool pdb installation doesn't appear to have been updated with the install_task changes.  This fixes it so the pdbs now get installed.
I encountered this issue in release 1.9.11
> Fix pdb installation in cs tool

- waflib/Tools/cs.py
Allow /noconfig compiler option to be used even when response files are in use.
> Allow /noconfig to be used with csc

- waflib/Tools/cs.py
Add new optional attribute `csdoc` to the cs tool that will enable xml documentation.
> Add xmldoc support to cs tool

- waflib/extras/resx.py
Add new optional attribute `namespace` to the resx tool.
Sometimes, C# assemblies have compiled resources that don't match the assembly name.  The current resx tool assigns the resource namespace to the assembly name.
For example, if the assembly is `My.dll` and the resource is `Path/To/MyResource.resx`, the tool names the resource `My.Path.To.MyResource`.  This optional attribute allows you to change the behavior.  Specifying `namespace='Other'` would change the resource to `Other.Path.To.MyResource`.
A real world example is BouncyCastle.  The assembly is named `BouncyCastle.dll` but the assembly namespace is `Org.BouncyCastle`.
> Allow overriding namespace of resx files.

- waflib/Scripting.py
When '--no-lock-in-top' command line option is activated, the default implementation of the 'distclean' command does nothing. 
This simple fix proposes a backward compatible solution to make it work if not lock file is available in top directory.
> Add distclean compatibility with '--no-lock-in-top' command line option

- waflib/Scripting.py
Waf does change directory as soon as it start executing the main wscript it has been invoked for, c.f. waflib.Scripting.py:waf_entry_point().
Because of this, it is not possible to support relative paths in module options. Those would be relative to the current working directory in which the main waf process is launched from (from the point of view of the user invoking it). 
By storing this path in Context.py, it is possible to write support relative paths in Options:
```
def options(opts):
currOptsGroup = opts.add_option_group('Custom Flow Options')
opts.option_groups['Custom_Flow_Options'] = currOptsGroup
currOptsGroup.add_option('--input-file', action='store', default=None, help="Path to module input file", dest='input_file')
def configure(cnf):
specifiedInputFile = …
```
> Store the path the main process had been invoked from in Context.user_dir

- waflib/Tools/waf_unit_test.py
`waf_unit_test.exec_command()` has a different behavior w.r.t. `Context:exec_command()` when trying to execute custom commands from a `run()` method defined in a waf_unit_test subclass. 
In `Context:exec_command()`, if the specified `cmd` is a string, the `shell` parameter to `Utils.subprocess.Popen` is set to `true`. 
This pull request proposes to uses the same approach for `waf_unit_test.exec_command()`
> Fix 'shell' attribute on waf_unit_test:exec_command() Popen call 

- waflib/Node.py
Python compiled  `*.pyc` and Vim `*.swp` are quite common, I think Waf can safely include them in default exclusion list.
> Default ignore Vim swap and Python Compiled files

- waflib/Tools/fc_config.py
- waflib/Tools/gfortran.py
Same as for `gcc`/`g++` really, but only make usable for `gfortran`.
> Backport old gfortran compiler support.

- waflib/extras/use_config.py
Change obscure error-within-error behavior that use_config can trigger to be less obscure.
> Teach use_config to more gracefully fail during options() call #2043

- waflib/Tools/ifort.py
Seems like one input variable in a function call was forgotten to remove after c3af6e3fad646f0c349426fe8f982eca7f499648.
> Fix for Intel Fortran Detection on Windows.

- playground/javatest/src/Nums.java
- playground/javatest/test/TestNums.java
- playground/javatest/test/testng.xml
- playground/javatest/wscript
- waflib/extras/javatest.py
Compared to the code in the java demo this integrates with the waf_unit_test so should be much easier to integrate with other languages unit tests (ie. pytest). It is also more versatile for different test environment and was testes with TestNG and JUnit.
>  javatest: extra to integrate java unit testing into standard waf_unit_test environment

- waflib/Tools/qt5.py
The patch solves concurrency issues when files are generated/converted on the fly by doing as ccroot or simillar, so generating filenames based on the self.idx. I tested with the demo (just copy multiple time same bld changing the target) and works fine.
There is just one more point that is not covered: the create_uic_task as the name there (ie. ui_xxx.h) is then explicitly set by the user in the source file, so this wouldn't work as it is not all internal bookkeeping.
Question: for the uic could we use a cache such as it is done for the moc files? (of course putting the same assumption that the transformation is identical). This could be the solution for the uic. 
In case should this caching be applied also to other stuff like qrc/qm? (although now they are covered for concurrency, it …
> qt5: resolve concurrency issues when files such as qm and qrc are used by multiple build tasks

- waflib/Tools/waf_unit_test.py
Red color is used for failed tests, green color is used for passed
tests.
See #2069.
> Unit test summary color scheme fixed to use green and red colors

- waflib/extras/pch.py
When shared library compiled with precompiled headers enabled, this
change prevents precompiled headers to activate on dependent targets.
Otherwise, there is an issue with -fPIC flag propagation.
> Fix strangle issue with precompiled headers and shared libraries

- demos/gdbus/main.c
- demos/gdbus/test.xml
- demos/gdbus/wscript
- waflib/Tools/gdbus.py
Adds support for generating dbus bindings using the newer gdbus-codegen
tool that is designed to replace the deprecated dbus-binding-tool tool
> gdbus: Add glib DBus bindings

- playground/protoc/incseparate/depinotherdir.proto
- playground/protoc/wscript
- waflib/extras/protoc.py
protoc extra already correctly had the scanner for dependencies and would build dependent .proto files. But if the dependency is in another directory then also the include path to that directory has to be passed to protoc via -I otherwise the file will not be found and execution will fail.
Added also a small example in protoc playground.
> protoc: add .proto dependencies also in include path otherwise protoc will fail if dependency is in another directory

- waflib/extras/eclipse.py
it was actually working anyway if the features were passed as a string (as in the playground example) but not if passed as a list
> eclipse: correct feature name to javac not java

- playground/pyqt5/src/sample.py
Minor change to playground example so it is trivial to make it work also with pyside2 (if pyside2 is auto-detected instead of pyqt5 or if it is forced with --pyqt5-pyside2 at waf configure)
> pyqt5: improve the sample in playground so can easily work also with pyside2

- playground/eclipse/wscript
- waflib/extras/eclipse.py
When CDT is not included in the project (ie. we just have Python and/or Java) the current implementation would not create automatically a call to waf for the build stage. This patch adds in such cases an external builder that automates the call to waf without the need to manually configure one.
> eclipse: generate an external builder when no CDT is used in the project

- waflib/Tools/qt5.py
Qt parses argument files differently than cl.exe or link.exe, see https://github.com/qt/qtbase/blob/5.11/src/tools/moc/main.cpp#L141. Avoiding the quoting and escaping from Task.quote_flag saves one from "too many files specified" moc/rcc error when command-line string is longer than 8191 character limit.
> Don't quote or escape arg file lines for moc/rcc
