waf-project/waf

- playground/swig/wscript
- waflib/extras/swig.py
Swig tool can easily handle swig -outdir parameter with this patch
> swig tool can handle -outdir parameter

- waflib/extras/gccdeps.py
The current code handles .. at the beginning of a path, but not within the path
> Handle .. within paths in gccdeps

- waflib/Configure.py
Enables usage of home folder/tilde ~ in Configure.find_files
> Enable usage of home folder/tilde ~ in Configure.find_files

- waflib/extras/cpplint.py
Added the option to specify the line length for the Waf tool cpplint.
As a result, the import statements changed, because the global variable for the line length in cpplint is confined to its module’s namespace.
> add option for line length to cpplint

- waflib/extras/qt4.py
> Fix qt4.py to use deque instead of list

- waflib/Tools/python.py
- waflib/extras/swig.py
Extend check_swig_version in order to behave similar to check_python_version.
> Extend check_swig_version

- waflib/Utils.py
Not sure if that's the best approach, but it's one that looks okay from my point of view.
> Fallback to run_regular_process if we can't pickle arguments

- demos/xcode6/wscript
- waflib/extras/xcode6.py
Updated docs. Tested the xcode6 tool in XCode 7 and it worked successfully.
> Updated docs for xcode6 tool. Also, xcode6 tool tested in XCode 7

- waflib/Tools/qt5.py
> qt5: qt5 5.7 detection, added also case with std=c++11 but no fPIC/fPIE

- waflib/Tools/waf_unit_test.py
Often when a unit test run via waf_unit_test has problems it is not immediate to study it by hand (or for example with gdb) since when waf runs it the library path is created dynamically by waf depending on the dependencies. 
This patch adds a new parameter ut_dumpenv which, if specified, is the name of a file (created where the test is executed, that is the test cwd) that will contain all the environment used by the test execution. This can be then sourced/exported to easily run the tests in the same environment they are run by waf. It was tested also with pytest where the PYTHONPATH has the same issues.
Example usage:
`bld.program(source='test/unit_test.cpp', includes=['src/'] , use=['GTEST','ex-lib-c'], target='unit_test', features='test', ut_dumpenv='envdump1.txt')`
Will create …
> waf_unit_test: add possibility to dump the environment variables before test run

- waflib/Tools/qt5.py
This option gives the possibility to search on the system (QT5_LIBDIR or library automatically
found) for libraries available instead of using the list hardcoded in the tool. The search is
done using a regexp that matches the same files as the ones used for library search with support
for dynamic/static and win32/unix.
This option can be useful in a couple of situations:
-) A Qt5 version that is not (yet) supported by waf and therefore waf doesn't have the libraries yet
-) A custom Qt5 version with many unofficial libraries (that otherwise have to be added by hand
or using --qtextralibs)
-) A very small Qt5 installation (ie. embedded systems) where otherwise waf configure will anyway check
for the big list of libraries (and not find most of them)
> qt5: add --qtlibsfromsys option to generate the list of Qt5 libraries by searching on the system

- waflib/Tools/c_config.py
> Import library files need to be installed into lib/ on Windows

- waflib/Tools/msvc.py
> Detect MSVS 15.0 Installation path (via vswhere)

- waflib/extras/syms.py
The export symbol regular expression processing is updated to make
several improvements:
* The export expression (export_symbols_regex) now applies to both
functions and global variables
* A named capture group is used to match symbols. This allows the
export expression to contain capture groups without disrupting the
expression matching
> syms: Improve symbol processing

- playground/protoc/inc/message.proto
- playground/protoc/inc/message_inc.proto
- playground/protoc/wscript
- waflib/extras/protoc.py
Fix bug described in #2009 and extend example in playground to include
described scenario.
> Fix protoc #2009

- waflib/Options.py
- waflib/Scripting.py
This pull request introduces the option parsing behaviour proposed for Waf in request https://github.com/waf-project/waf/pull/2021 ( Details in link )
> Improve options management

- waflib/extras/cfg_cross_gnu.py
- waflib/extras/cross_gnu.py
I've added an illustrative example + considered DEST_OS in the code
> also use DEST_OS in cfg_cross_gnu

- waflib/Tools/ifort.py
> Use correct batch filed and function for Intel Fortran detection on Windows

- waflib/extras/parallel_debug.py
Without the task name/target it is not obvious which steps in the build take
the most of the build time.
Tested the SVG output with Firefox 52.
> Added task target to output of parallel_debug.

- waflib/extras/eclipse.py
> eclipse: give a better name to waf variable indicating the waf executable path
